/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.stopmario.view;

import lib.som.modelSom;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Tela Dificiculdade
 *
 * @author Juliano
 * @version 1.1
 */
public class TelaDificuldade extends javax.swing.JFrame {

    private String nome;
    private String dificuldade;
    private final modelSom som;
    private final TelaTabela tel;

    /**
     * Creates new form TelaDificuldade
     */
    public TelaDificuldade() {
        initComponents();
        tel = new TelaTabela();
        som = new modelSom();

    }

    private void comecar() {
        nome = txtNome.getText();
        dificuldade = cmbDif.getSelectedItem().toString();

        if (nome != null && !nome.isEmpty()){
        TelaTabela.lblNome.setText(nome);
        TelaTabela.lblDifi.setText(dificuldade);
        tel.adicionarNovoJogadorEPontos();
        tel.setVisible(true);
        som.pararComeco();
        this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "O nome nao pode estar vazio");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbLogo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cmbDif = new javax.swing.JComboBox<>();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbLogo.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        lbLogo.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 282, 100));

        jButton1.setBackground(new java.awt.Color(207, 81, 12));
        jButton1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Entrar");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 120, 30));

        cmbDif.setBackground(new java.awt.Color(92, 148, 252));
        cmbDif.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        cmbDif.setForeground(new java.awt.Color(255, 255, 255));
        cmbDif.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facil", "Medio", "Dificil", " " }));
        cmbDif.setBorder(null);
        cmbDif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDifActionPerformed(evt);
            }
        });
        getContentPane().add(cmbDif, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 170, 120, -1));

        txtNome.setBackground(new java.awt.Color(92, 148, 252));
        txtNome.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        txtNome.setBorder(null);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 120, 30));

        jLabel2.setBackground(new java.awt.Color(0, 153, 51));
        jLabel2.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GRAU:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 153, 51));
        jLabel3.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOME:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        lbFundo.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        lbFundo.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 2, 500, 290));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void cmbDifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDifActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        comecar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Definir a imagem de ícone da aplicação
        this.getContentPane().setBackground(Color.WHITE);
        this.setIconImage(new ImageIcon(getClass().getResource("/lib/img/Logo.png")).getImage());

        {
            ImageIcon imagem = new ImageIcon(TelaTabela.class.getResource("/lib/img/Logo.png"));
            Image imag = imagem.getImage().getScaledInstance(lbLogo.getWidth(), lbLogo.getHeight(), Image.SCALE_DEFAULT);
            lbLogo.setIcon(new ImageIcon(imag));
        }
        {
            ImageIcon imagem = new ImageIcon(TelaTabela.class.getResource("/lib/img/fundo.png"));
            Image imag = imagem.getImage().getScaledInstance(lbFundo.getWidth(), lbFundo.getHeight(), Image.SCALE_DEFAULT);
            lbFundo.setIcon(new ImageIcon(imag));
        }

        som.somComeco();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDificuldade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDificuldade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDificuldade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDificuldade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDificuldade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbDif;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbFundo;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
